// Pre-projects world land outlines into compact SVG path strings.
// Output: src/data/map-data.js (window.MAP_DATA), consumed at runtime with the same projection params.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { geoConicConformal, geoEqualEarth, geoPath } from 'd3-geo';
import { feature } from 'topojson-client';

const root = new URL('..', import.meta.url);
const read = (p) => JSON.parse(readFileSync(new URL(p, root)));
const land50 = feature(read('node_modules/world-atlas/land-50m.json'), 'land');
const land110 = feature(read('node_modules/world-atlas/land-110m.json'), 'land');

// Records projected + clipped rings through d3's stream pipeline.
function rings(projection, geo) {
  const out = [];
  let cur = null;
  const ctx = {
    moveTo(x, y) { cur = [[x, y]]; out.push(cur); },
    lineTo(x, y) { cur.push([x, y]); },
    closePath() {},
    arc() {}, rect() {}
  };
  geoPath(projection, ctx)(geo);
  return out;
}

// Ramer-Douglas-Peucker on a polyline.
function simplify(pts, tol) {
  if (pts.length < 4) return pts;
  const keep = new Uint8Array(pts.length);
  keep[0] = keep[pts.length - 1] = 1;
  const stack = [[0, pts.length - 1]];
  const t2 = tol * tol;
  while (stack.length) {
    const [a, b] = stack.pop();
    const [ax, ay] = pts[a], [bx, by] = pts[b];
    const dx = bx - ax, dy = by - ay, len2 = dx * dx + dy * dy || 1e-9;
    let max = -1, idx = -1;
    for (let i = a + 1; i < b; i++) {
      const [px, py] = pts[i];
      let t = ((px - ax) * dx + (py - ay) * dy) / len2;
      t = Math.max(0, Math.min(1, t));
      const qx = ax + t * dx - px, qy = ay + t * dy - py;
      const d2 = qx * qx + qy * qy;
      if (d2 > max) { max = d2; idx = i; }
    }
    if (max > t2) { keep[idx] = 1; stack.push([a, idx], [idx, b]); }
  }
  return pts.filter((_, i) => keep[i]);
}

function area(r) {
  let s = 0;
  for (let i = 0, j = r.length - 1; i < r.length; j = i++) s += (r[j][0] + r[i][0]) * (r[j][1] - r[i][1]);
  return Math.abs(s / 2);
}

function toPath(rs, tol, minArea, digits) {
  const f = (v) => {
    const s = v.toFixed(digits);
    return s.includes('.') ? s.replace(/0+$/, '').replace(/\.$/, '') : s;
  };
  let d = '';
  let n = 0;
  for (const r of rs) {
    const s = simplify(r, tol);
    if (s.length < 3 || area(s) < minArea) continue;
    d += 'M' + f(s[0][0]) + ' ' + f(s[0][1]);
    for (let i = 1; i < s.length; i++) d += 'L' + f(s[i][0]) + ' ' + f(s[i][1]);
    d += 'Z';
    n += s.length;
  }
  return { d, n };
}

// Route map: Lambert conformal conic over Europe and the North Atlantic.
const RW = 1000, RH = 560;
const route = geoConicConformal().parallels([40, 62]).rotate([20, 0]).center([0, 51]);
route.fitExtent([[24, 24], [RW - 24, RH - 24]], {
  type: 'MultiPoint',
  coordinates: [[-76.5, 39.2], [41, 56.5], [-72, 45.5], [30, 61.5], [-9, 37.5], [-22, 64]]
});
route.clipExtent([[-160, -160], [RW + 160, RH + 160]]);
const routeLand = toPath(rings(route, land50), 0.12, 0.02, 1);
// Coarse backdrop in the same projection for zoomed-out views beyond the detailed clip box.
const routeWide = geoConicConformal().parallels([40, 62]).rotate(route.rotate()).center(route.center())
  .scale(route.scale()).translate(route.translate()).clipExtent([[-1400, -1000], [RW + 1400, RH + 1000]]);
const routeLand110 = toPath(rings(routeWide, land110), 0.5, 2, 0);

// World map: Equal Earth.
const WW = 1000;
const world = geoEqualEarth().fitWidth(WW, { type: 'Sphere' });
const [[, y0], [, y1]] = geoPath(world).bounds({ type: 'Sphere' });
const WH = Math.ceil(y1 - y0);
const worldLand = toPath(rings(world, land110), 0.35, 0.4, 1);

const data = {
  route: {
    w: RW, h: RH,
    parallels: [40, 62], rotate: route.rotate(), center: route.center(),
    scale: route.scale(), translate: route.translate(),
    clip: [[-160, -160], [RW + 160, RH + 160]],
    land: routeLand.d,
    land110: routeLand110.d
  },
  world: {
    w: WW, h: WH,
    scale: world.scale(), translate: world.translate(),
    land: worldLand.d
  }
};

mkdirSync(new URL('src/data/', root), { recursive: true });
writeFileSync(new URL('src/data/map-data.js', root),
  '// Generated by tools/build-map.mjs from world-atlas@2.0.2 (Natural Earth). Do not edit by hand.\n' +
  'window.MAP_DATA = ' + JSON.stringify(data) + ';\n');

console.log('route land points:', routeLand.n, 'chars:', routeLand.d.length);
console.log('route backdrop points:', routeLand110.n, 'chars:', routeLand110.d.length);
console.log('world land points:', worldLand.n, 'chars:', worldLand.d.length, 'height:', WH);
